PKGNAMESUFFIX=	-daemon
COMMENT=	Virtual Peer-to-Peer Currency Software
MASTERDIR=	${.CURDIR}/../novacoin
DESCR=		${MASTERDIR}/pkg-descr
SLAVE_PORT=	yes
OPTIONS_EXCLUDE=	X11 DBUS QRCODES
.include "${MASTERDIR}/Makefile"
